# Generated by Django 3.1.6 on 2021-03-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='poast',
            new_name='post',
        ),
    ]
